# Notebook 02 – Master Dataset Construction

## Objective

Merge all processed indicators into a single analytical dataset that will be used to construct the Climate Resilience Index for the 32 Mexican states.

## Inputs

Processed indicator datasets:

- Hazard
  - Drought Vulnerability
--------------
- Sensitivity
  - Multidimensional Poverty
  - Marginalization Index
  - Employment in the Primary Sector
--------------
- Adaptive Capacity
  - Educational Attainment

## Output

- climate_resilience_master.csv

In [6]:
import pandas as pd
import numpy as np

In [7]:
drought = pd.read_csv(
    "../data/processed/hazard_drought.csv"
)

poverty = pd.read_csv(
    "../data/processed/sensitivity_multidimensional_poverty.csv"
)

marginalization = pd.read_csv(
    "../data/processed/sensitivity_marginalization.csv"
)

employment = pd.read_csv(
    "../data/processed/sensitivity_primary_sector_employment.csv"
)

education = pd.read_csv(
    "../data/processed/adaptive_capacity_educational_attainment.csv"
)

state_lookup = pd.read_csv(
    "../data/state_codes.csv"
)

In [8]:
datasets = {
    "Drought": drought,
    "Poverty": poverty,
    "Marginalization": marginalization,
    "Employment": employment,
    "Education": education
}

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.shape)
    print(df.head(2))

Drought
(32, 3)
   state_code       state_name  drought_susceptibility
0           1   Aguascalientes                   52.53
1           2  Baja California                   64.80

Poverty
(32, 3)
   state_code       state_name  multidimensional_poverty
0           1   Aguascalientes                  23.72232
1           2  Baja California                  13.37082

Marginalization
(32, 3)
   state_code       state_name  marginalization_index
0           1   Aguascalientes              22.205721
1           2  Baja California              21.380297

Employment
(32, 3)
   state_code       state_name  primary_sector_employment
0           1   Aguascalientes                       4.17
1           2  Baja California                       5.03

Education
(32, 3)
   state_code       state_name  educational_attainment
0           1   Aguascalientes                   10.35
1           2  Baja California                   10.20

In [9]:
master = state_lookup.copy()

master.head()

   state_code            state_name
0           1        Aguascalientes
1           2       Baja California
2           3   Baja California Sur
3           4              Campeche
4           5  Coahuila de Zaragoza

In [10]:
master = master.merge(
    drought,
    on=["state_code", "state_name"],
    how="left"
)

In [11]:
master = master.merge(
    poverty,
    on=["state_code", "state_name"],
    how="left"
)

In [12]:
master = master.merge(
    marginalization,
    on=["state_code", "state_name"],
    how="left"
)

In [13]:
master = master.merge(
    employment,
    on=["state_code", "state_name"],
    how="left"
)

In [14]:
master = master.merge(
    education,
    on=["state_code", "state_name"],
    how="left"
)

In [16]:
master.head()

,state_code,state_name,drought_susceptibility,multidimensional_poverty,marginalization_index,primary_sector_employment,educational_attainment
0,1,Aguascalientes,52.530000,23.722320,22.205721,4.17,10.35
1,2,Baja California,64.800000,13.370820,21.380297,5.03,10.20
2,3,Baja California Sur,31.106000,13.329031,21.473388,6.39,10.34
3,4,Campeche,14.763636,45.129444,17.805051,16.08,9.63
4,5,Coahuila de Zaragoza,31.983684,18.243322,22.545684,2.98,10.43

In [17]:
master.describe()

,state_code,drought_susceptibility,multidimensional_poverty,marginalization_index,primary_sector_employment,educational_attainment
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,16.500000,48.824808,34.541128,19.260619,11.525313,9.722188
std,9.380832,12.304669,14.928986,2.956503,7.570266,0.787535
min,1.000000,14.763636,13.329031,10.989156,0.450000,7.780000
25%,8.750000,41.107873,21.692513,17.991146,5.090000,9.340000
50%,16.500000,52.235454,33.672686,19.842337,10.530000,9.835000
75%,24.250000,57.139957,44.444277,21.386633,16.227500,10.225000
max,32.000000,68.122500,67.370830,23.444318,31.350000,11.480000

In [11]:
master.shape

(32, 7)

In [12]:
master.isna().sum()

state_code                   0
state_name                   0
drought_susceptibility       0
multidimensional_poverty     0
marginalization_index        0
primary_sector_employment    0
educational_attainment       0
dtype: int64

In [13]:
master.duplicated(subset="state_name").sum()

np.int64(0)

In [14]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   state_code                 32 non-null     int64
 1   state_name                 32 non-null     object
 2   drought_susceptibility     32 non-null     float64
 3   multidimensional_poverty   32 non-null     float64
 4   marginalization_index      32 non-null     float64
 5   primary_sector_employment  32 non-null     float64
 6   educational_attainment     32 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 1.9+ KB

In [15]:
master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [16]:
basic_services = pd.read_csv(
    "../data/processed/adaptive_capacity_basic_services.csv"
)

In [17]:
master = master.merge(
    basic_services,
    on=["state_code", "state_name"],
    how="left"
)

In [18]:
master.shape

(32, 9)

In [19]:
master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [20]:
health = pd.read_csv(
    "../data/processed/adaptive_capacity_health_service_affiliation.csv"
)

In [21]:
master = master.merge(
    health,
    on=["state_code", "state_name"],
    how="left"
)

In [22]:
master.shape

(32, 10)

In [23]:
master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [24]:
population_density = pd.read_csv("../data/processed/exposure_population_density.csv")

In [25]:
population_density.head()

   state_code            state_name  population_density
0           1        Aguascalientes               253.9
1           2       Baja California                52.8
2           3   Baja California Sur                10.8
3           4              Campeche                16.1
4           5  Coahuila de Zaragoza                20.8

In [26]:
master = master.merge(
    population_density,
    on=["state_code", "state_name"],
    how="left"
)

In [27]:
master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [28]:
agricultural_land = pd.read_csv("../data/processed/exposure_agricultural_land.csv")

In [29]:
master = master.merge(
    agricultural_land,
    on=["state_code", "state_name"],
    how="left"
)

In [30]:
master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [31]:
hazard = pd.read_csv("../data/processed/hazard_indicators.csv")

master = master.merge(
    hazard,
    on=["state_code", "state_name"],
    how="left"
)

In [32]:
master.head()

,state_code,state_name,drought_susceptibility,multidimensional_poverty,marginalization_index,primary_sector_employment,educational_attainment,access_to_piped_water,access_to_drainage,health_service_affiliation,population_density,agricultural_land_share,flood_hazard,cyclone_hazard,drought_hazard
0,1,Aguascalientes,52.530000,23.722320,22.205721,4.17,10.35,95.27,99.26,81.45,253.9,55.86,2.80,1.00,2.00
1,2,Baja California,64.800000,13.370820,21.380297,5.03,10.20,92.91,96.27,77.08,52.8,33.23,3.34,1.49,4.24
2,3,Baja California Sur,31.106000,13.329031,21.473388,6.39,10.34,82.29,96.87,83.18,10.8,20.54,2.32,4.98,2.98
3,4,Campeche,14.763636,45.129444,17.805051,16.08,9.63,64.69,94.40,77.52,16.1,55.75,4.79,3.12,3.00
4,5,Coahuila de Zaragoza,31.983684,18.243322,22.545684,2.98,10.43,92.51,98.52,80.74,20.8,44.36,2.94,1.18,2.96

In [33]:
master.columns

Index(['state_code', 'state_name', 'drought_susceptibility',
       'multidimensional_poverty', 'marginalization_index',
       'primary_sector_employment', 'educational_attainment',
       'access_to_piped_water', 'access_to_drainage',
       'health_service_affiliation', 'population_density',
       'agricultural_land_share', 'flood_hazard', 'cyclone_hazard',
       'drought_hazard'],
      dtype='object')

In [34]:
master = master.drop(columns=["drought_susceptibility"])

In [35]:
master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [36]:
master["state_code"] = (
    master["state_code"]
    .astype(str)
    .str.zfill(2)
)

master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [37]:
master["marginalization_score"] = (
    master["marginalization_index"].max()
    - master["marginalization_index"]
).round(2)

master.drop(
    columns=["marginalization_index"],
    inplace=True
)

In [38]:
master.to_csv(
    "../data/processed/climate_resilience_master.csv",
    index=False
)

In [39]:
master.head()

,state_code,state_name,multidimensional_poverty,primary_sector_employment,educational_attainment,access_to_piped_water,access_to_drainage,health_service_affiliation,population_density,agricultural_land_share,flood_hazard,cyclone_hazard,drought_hazard,marginalization_score
0,01,Aguascalientes,23.722320,4.17,10.35,95.27,99.26,81.45,253.9,55.86,2.80,1.00,2.00,1.24
1,02,Baja California,13.370820,5.03,10.20,92.91,96.27,77.08,52.8,33.23,3.34,1.49,4.24,2.06
2,03,Baja California Sur,13.329031,6.39,10.34,82.29,96.87,83.18,10.8,20.54,2.32,4.98,2.98,1.97
3,04,Campeche,45.129444,16.08,9.63,64.69,94.40,77.52,16.1,55.75,4.79,3.12,3.00,5.64
4,05,Coahuila de Zaragoza,18.243322,2.98,10.43,92.51,98.52,80.74,20.8,44.36,2.94,1.18,2.96,0.90

In [42]:
master.describe()

,multidimensional_poverty,primary_sector_employment,educational_attainment,access_to_piped_water,access_to_drainage,health_service_affiliation,population_density,agricultural_land_share,flood_hazard,cyclone_hazard,drought_hazard,marginalization_score
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,34.541128,11.525313,9.722188,77.561250,95.344062,75.655000,309.684375,52.718437,3.646562,1.908750,2.740312,4.183750
std,14.928986,7.570266,0.787535,14.615586,3.889490,5.747437,1078.690324,12.867016,0.731259,1.082672,0.629349,2.957295
min,13.329031,0.450000,7.780000,40.620000,80.340000,62.220000,10.800000,20.540000,2.320000,1.000000,1.670000,0.000000
25%,21.692513,5.090000,9.340000,66.877500,94.745000,71.535000,43.400000,43.695000,3.087500,1.085000,2.150000,2.055000
50%,33.672686,10.530000,9.835000,79.085000,96.390000,77.300000,67.150000,52.480000,3.560000,1.455000,2.925000,3.600000
75%,44.444277,16.227500,10.225000,89.720000,97.387500,80.770000,159.050000,60.937500,4.155000,2.210000,3.030000,5.452500
max,67.370830,31.350000,11.480000,97.070000,99.710000,84.350000,6163.300000,81.900000,5.000000,4.980000,4.240000,12.460000